### ISSUE TITLE
git:// doesn't work when cloning locally

### ISSUE THREAD

**Issue by Parking-Master** [defunctzombie/localtunnel-server#201]
I found [this](https://stackoverflow.com/questions/72915782/fatal-unable-to-connect-to-github-com-github-com0-140-82-121-3-errno-opera) problem with git after copying the command from the docs:
```
$ git clone https://github.com/defunctzombie/localtunnel-server.git

Cloning into 'localtunnel-server'...
remote: Enumerating objects: 770, done.
remote: Total 770 (delta 0), reused 0 (delta 0), pack-reused 770
Receiving objects: 100% (770/770), 436.21 KiB | 2.78 MiB/s, done.
Resolving deltas: 100% (412/412), done.
```

I found out that the `git://` protocol no longer works and only works with `https://` or `ssh://`.

Could you update the docs and change this minor detail?

Thanks!

**Comment by j-peace** [comment]
Hii Parker,

Which node version are you using?

**Comment by Parking-Master** [comment]
It's not Node, it's git. And in the stackoverflow anwser I linked, they said that "git://" is no longer valid.

**Comment by j-peace** [comment]
All rigth I got it.


Try it and let me know if its work for you.

<pre>
git clone https://github.com/localtunnel/server
</pre>

![image](https://github.com/localtunnel/server/assets/81580990/9474973f-5340-4f84-9c1c-a231439d316c)

**Comment by Parking-Master** [comment]
Thanks! It does work, the issue was basically asking someone to change the docs because it's outdated

**Comment by j-peace** [comment]
No problem :+1: 

Yes! unfortunaly the repository is a bit old and maybe in that time it worked.

So, I have this repository and maybe it can help you: 

<pre>
https://github.com/tiagopazhs/localtunnelServer-raise
</pre>

I recomend you to see this two commits: 

<h3>Fix esm modules</h3>

It will help you to setup the project because there are some differences between node versions.

<pre>
https://github.com/tiagopazhs/localtunnelServer-raise/commit/425c9733393a13dedd32a363c325a076d4006cbf
</pre>


<h3>Run server in your machine</h3>

If you debug your application you will got this problem because localtunnel uses an especific lib that don't handle with local urls.

<pre>
https://github.com/tiagopazhs/localtunnelServer-raise/commit/518214b9163b4cc80b50f2d9d36686904179f344
</pre

Let me know if you have new issues in the future.

**Comment by Parking-Master** [comment]
Thank you!
